version: '3.9'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: sport_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
 pg: